package example:bash;

interface bash {
    resource bash-runner {
        constructor();

        write-string: func(path: string, contents: string) -> result<_, string>;
        read-string: func(path: string) -> result<string, string>;
        list-files: func() -> result<list<string>, string>;

        execute: func(bash-script: string) -> result<string, string>;
    }

    run-simple: func(bash-script: string) -> result<string, string>;
}

world main {
    export bash;
}
